In [77]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv(r"D:\Movie_recommended_system\data\movies.csv")
df

,index,genres,title
0,0,Action Adventure Fantasy Science Fiction,Avatar
1,1,Adventure Fantasy Action,Pirates of the Caribbean: At World's End
2,2,Action Adventure Crime,Spectre
3,3,Action Crime Drama Thriller,The Dark Knight Rises
4,4,Action Adventure Science Fiction,John Carter
...,...,...,...
4688,4688,Foreign Thriller,Cavite
4689,4689,Action Crime Thriller,El Mariachi
4690,4690,Comedy Romance,Newlyweds
4691,4691,Comedy Drama Romance TV Movie,"Signed, Sealed, Delivered"
4692,4692,Documentary,My Date with Drew

In [79]:
df.head()

,index,genres,title
0,0,Action Adventure Fantasy Science Fiction,Avatar
1,1,Adventure Fantasy Action,Pirates of the Caribbean: At World's End
2,2,Action Adventure Crime,Spectre
3,3,Action Crime Drama Thriller,The Dark Knight Rises
4,4,Action Adventure Science Fiction,John Carter

In [80]:
df.shape

(4693, 3)

In [81]:
df.columns.tolist()

['index', 'genres', 'title']

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4693 entries, 0 to 4692
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   4693 non-null   int64
 1   genres  4666 non-null   str
 2   title   4693 non-null   str
dtypes: int64(1), str(2)
memory usage: 110.1 KB

In [83]:
df.isna().sum()

index      0
genres    27
title      0
dtype: int64

In [84]:
df.duplicated().sum()

np.int64(0)

In [85]:
df['title'].duplicated().sum()

np.int64(2)

In [86]:
df['genres'].duplicated().sum()

np.int64(3555)

In [87]:
df[df['title'].duplicated()]

      index                                         genres            title
3614   3614                                          Drama  Out of the Blue
4171   4171  Family Adventure Comedy Science Fiction Crime           Batman

In [88]:
df.loc[[3614,4171],['genres','title']]

                                             genres            title
3614                                          Drama  Out of the Blue
4171  Family Adventure Comedy Science Fiction Crime           Batman

In [89]:
df['genres'].nunique()

1137

In [90]:
df['title'].nunique()

4691

In [91]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
index,4693.0,NaN,NaN,NaN,2346.0,1354.896737,0.0,1173.0,2346.0,3519.0,4692.0
genres,4666,1137,Drama,362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,4693,4691,Batman,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
df.isna().sum()

index      0
genres    27
title      0
dtype: int64

In [93]:
df.dropna(subset=['genres'],inplace=True)

In [94]:
df.isna().sum()

index     0
genres    0
title     0
dtype: int64

In [95]:
df.shape

(4666, 3)

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [97]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(df['genres'])
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12343 stored elements and shape (4666, 22)>
  Coords	Values
  (0, 0)	0.35903119212216394
  (0, 1)	0.4129302770799773
  (0, 8)	0.5072564746038137
  (0, 17)	0.47078448271289786
  (0, 9)	0.47078448271289786
  (1, 0)	0.4811851676700948
  (1, 1)	0.5534224573590233
  (1, 8)	0.6798414654204339
  (2, 0)	0.5155296026840344
  (2, 1)	0.5929228054558979
  (2, 4)	0.6186047005372246
  (3, 0)	0.5089055842412188
  (3, 4)	0.610656274445227
  (3, 6)	0.36260910785806355
  (3, 18)	0.4864449153883293
  (4, 0)	0.4166085118068071
  (4, 1)	0.4791513160665072
  (4, 17)	0.5462835180571768
  (4, 9)	0.5462835180571768
  (5, 0)	0.4811851676700948
  (5, 1)	0.5534224573590233
  (5, 8)	0.6798414654204339
  (6, 2)	0.7812090308238484
  (6, 7)	0.6242695332620867
  (7, 0)	0.4166085118068071
  :	:
  (4654, 12)	0.6718446979217755
  (4655, 6)	1.0
  (4656, 12)	1.0
  (4657, 6)	1.0
  (4658, 18)	0.5231058336569835
  (4658, 3)	0.4515021677956472
  (4658, 12)	0.7228458198467108
  (4659, 6)	1.0
  (4660, 17)	0.594789173363792
  (4660, 9)	0.594789173363792
  (4660, 6)	0.3232024080245719
  (4660, 18)	0.4335803062242938
  (4661, 18)	0.36272962843340917
  (4661, 10)	0.9318944235569611
  (4662, 0)	0.5460704124867121
  (4662, 4)	0.6552518463146689
  (4662, 18)	0.5219694651105653
  (4663, 3)	0.6011602932110565
  (4663, 16)	0.7991284639320494
  (4664, 6)	0.15889195981291585
  (4664, 3)	0.1839785358227009
  (4664, 16)	0.24456453027386754
  (4664, 19)	0.6637369335795879
  (4664, 13)	0.6637369335795879
  (4665, 5)	1.0

In [98]:
from sklearn.metrics.pairwise import cosine_similarity

In [99]:
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.74613936 0.42992699 ... 0.         0.         0.        ]
 [0.74613936 1.         0.57620199 ... 0.         0.         0.        ]
 [0.42992699 0.57620199 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.30603907 0.        ]
 [0.         0.         0.         ... 0.30603907 1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [110]:
similarity.shape

(4666, 4666)

In [100]:
list_of_all_titles = df['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', '4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur et les Minimoys', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Don Gato: El inicio de la pandilla', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Deux frères', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', "Michael Jackson's This Is It", 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'Un long dimanche de fiançailles', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'The Adventures of Ford Fairlane', 'The Boat That Rocked', 'Traffic', 'Indiana Jones and the Last Crusade', 'Anna Karenina', 'Chappie', 'The Bone Collector', 'Panic Room', 'Th

In [101]:
movie_name = input('enter your favourite movie name : ')

In [102]:
import difflib
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

In [103]:
find_close_match

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [118]:
close_match = find_close_match[0]
print(close_match)

Iron Man

In [121]:
index_of_the_movie = df[df.title == close_match]['index'].values[0]

In [122]:
print(index_of_the_movie)

67

In [107]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.8617951432750772)), (1, np.float64(0.46563893539088363)), (2, np.float64(0.49887376312658926)), (3, np.float64(0.21201439810090789)), (4, np.float64(1.0000000000000002)), (5, np.float64(0.46563893539088363)), (6, np.float64(0.0)), (7, np.float64(1.0000000000000002)), (8, np.float64(0.24469295275538902)), (9, np.float64(0.46563893539088363)), (10, np.float64(0.8617951432750772)), (11, np.float64(0.4474917333880216)), (12, np.float64(0.46563893539088363)), (13, np.float64(0.3753240714679057)), (14, np.float64(0.8617951432750772)), (15, np.float64(0.24469295275538902)), (16, np.float64(1.0000000000000002)), (17, np.float64(0.46563893539088363)), (18, np.float64(0.8173023338214698)), (19, np.float64(0.46563893539088363)), (20, np.float64(0.46563893539088363)), (21, np.float64(0.6349398678600585)), (22, np.float64(0.30249527459983805)), (23, np.float64(0.30249527459983805)), (24, np.float64(0.5751843236377825)), (25, np.float64(0.0)), (26, np.float64(1.0000000000000002)), (27, np.float64(0.9290453925250155)), (28, np.float64(0.9290453925250155)), (29, np.float64(0.5379003219367802)), (30, np.float64(0.46563893539088363)), (31, np.float64(1.0000000000000002)), (32, np.float64(0.24469295275538902)), (33, np.float64(0.9290453925250155)), (34, np.float64(0.0)), (35, np.float64(1.0000000000000002)), (36, np.float64(1.0000000000000002)), (37, np.float64(0.24469295275538902)), (38, np.float64(0.46563893539088363)), (39, np.float64(1.0000000000000002)), (40, np.float64(0.21611604056764613)), (41, np.float64(0.9290453925250155)), (42, np.float64(0.0)), (43, np.float64(0.7993144266420142)), (44, np.float64(0.41660851180680714)), (45, np.float64(0.6705809051473737)), (46, np.float64(0.8617951432750772)), (47, np.float64(1.0000000000000002)), (48, np.float64(0.1911659918442979)), (49, np.float64(0.0)), (50, np.float64(0.41181344123080416)), (51, np.float64(1.0000000000000002)), (52, np.float64(1.0000000000000002)), (53, np.float64(0.6349398678600585)), (54, np.float64(0.22840121087133897)), (55, np.float64(0.35329921962559263)), (56, np.float64(1.0000000000000002)), (57, np.float64(0.0)), (58, np.float64(0.2074194505173765)), (59, np.float64(0.0)), (60, np.float64(0.8617951432750772)), (61, np.float64(0.6349398678600585)), (62, np.float64(0.24469295275538902)), (63, np.float64(0.7725615601373472)), (64, np.float64(0.21201439810090789)), (65, np.float64(0.21611604056764613)), (66, np.float64(0.651880282786496)), (67, np.float64(1.0000000000000002)), (68, np.float64(0.2911061909310497)), (69, np.float64(0.7315159960267821)), (70, np.float64(0.46563893539088363)), (71, np.float64(0.7914700916020292)), (72, np.float64(0.0)), (73, np.float64(0.8777323147245603)), (74, np.float64(0.6349398678600585)), (75, np.float64(0.9290453925250155)), (76, np.float64(0.0)), (77, np.float64(0.2332955253801762)), (78, np.float64(1.0000000000000002)), (79, np.float64(0.2817147770928973)), (80, np.float64(0.35877555672910555)), (81, np.float64(0.7639060605607628)), (82, np.float64(0.9095579740208651)), (83, np.float64(0.4404692075069341)), (84, np.float64(1.0000000000000002)), (85, np.float64(0.18903845008879386)), (86, np.float64(0.6714186581201941)), (87, np.float64(0.35329921962559263)), (88, np.float64(0.21611604056764613)), (89, np.float64(0.1970962638552968)), (90, np.float64(1.0000000000000002)), (91, np.float64(0.1970962638552968)), (92, np.float64(0.7993144266420142)), (93, np.float64(1.0000000000000002)), (94, np.float64(0.8641819623026593)), (95, np.float64(0.8050599033877955)), (96, np.float64(0.46563893539088363)), (97, np.float64(0.22749758188781843)), (98, np.float64(0.0)), (99, np.float64(1.0000000000000002)), (100, np.float64(1.0000000000000002)), (101, np.float64(0.41235220628219355)), (102, np.float64(0.5001036536817958)), (103, np.float64(0.0)), (104, np.float64(0.18903845008879386)), (105, np.float64(0.46563893539088363)), (106, np.float64(0.9290453925250155)), (107, np.float64(0.24469295275538902)), (108, np.float64(0.0)), (109, np.float64(1.0000000000000002)), (110, np.float64(0.3161799037806855)), (111, np.float64(0.20415305531403358)), (112, np.float64(0.24469295275538902)), (113, np.float64(0.24068395608755438)), (114, np.float64(0.6705809051473737)), (115, np.float64(0.2297615049804784)), (116, np.float64(0.0)), (117, np.float64(0.2426595727913571)), (118, np.float64(0.0)), (119, np.float64(0.3723872764105476)), (120, np.float64(0.9290453925250155)), (121, np.float64(0.9290453925250155)), (122, np.float64(0.22840121087133897)), (123, np.float64(0.9290453925250155)), (124, np.float64(0.46563893539088363)), (125, np.float64(0.9290453925250155)), (126, np.float64(0.0)), (127, np.float64(0.46563893539088363)), (128, np.float64(0.21611604056764613)), (129, np.float64(0.3723872764105476)), (130, np.float64(0.47915131606650724)), (131, np.float64(0.0)), (132, np.float64(0.5379003219367802)), (133, np.float64(0.0)), (134, np.float64(0.21611604056764613)), (135, np.float64(0.0)), (136, np.float64(0.3927046456875748)), (137, np.float64(0.5379003219367802)), (138, np.float64(0.2677301804951162)), (139, np.float64(0.22840121087133897)), (140, np.float64(0.21611604056764613)), (141, np.float64(0.24469295275538902)), (142, np.float64(0.22840121087133897)), (143, np.float64(0.23919394623357615)), (144, np.float64(0.0)), (145, np.float64(0.5379003219367802)), (146, np.float64(0.21726655613463464)), (147, np.float64(0.9290453925250155)), (148, np.float64(0.9456976068460856)), (149, np.float64(0.4298383551122527)), (150, np.float64(0.35329921962559263)), (151, np.float64(0.5379003219367802)), (152, np.float64(0.0)), (153, np.float64(0.0)), (154, np.float64(0.14688699329647817)), (155, np.float64(0.5751843236377825)), (156, np.float64(1.0000000000000002)), (157, np.float64(0.24068395608755438)), (158, np.float64(0.3477146109308615)), (159, np.float64(0.0)), (160, np.float64(0.41660851180680714)), (161, np.float64(0.716934294431677)), (162, np.float64(0.4180968555740999)), (163, np.float64(0.8314692706543022)), (164, np.float64(0.9290453925250155)), (165, np.float64(0.4044156323485472)), (166, np.float64(0.7406437932326532)), (167, np.float64(1.0000000000000002)), (168, np.float64(0.5379003219367802)), (169, np.float64(0.47915131606650724)), (170, np.float64(0.2457305803491617)), (171, np.float64(0.0)), (172, np.float64(1.0000000000000002)), (173, np.float64(0.24469295275538902)), (174, np.float64(0.20727206741726545)), (175, np.float64(0.0)), (176, np.float64(0.16748037264232096)), (177, np.float64(0.21611604056764613)), (178, np.float64(0.1934934160699502)), (179, np.float64(0.21611604056764613)), (180, np.float64(1.0000000000000002)), (181, np.float64(1.0000000000000002)), (182, np.float64(0.43973468792022047)), (183, np.float64(0.8326987906296466)), (184, np.float64(0.4180968555740999)), (185, np.float64(0.32588170636491576)), (186, np.float64(0.2050469081351088)), (187, np.float64(0.40731910906486923)), (188, np.float64(0.2198582793237303)), (189, np.float64(0.24469295275538902)), (190, np.float64(0.0)), (191, np.float64(1.0000000000000002)), (192, np.float64(0.0)), (193, np.float64(0.2297615049804784)), (194, np.float64(0.5962771999364336)), (195, np.float64(0.24469295275538902)), (196, np.float64(0.1841767580698868)), (197, np.float64(0.46563893539088363)), (198, np.float64(0.8326987906296466)), (199, np.float64(0.0)), (200, np.float64(0.21611604056764613)), (201, np.float64(0.9290453925250155)), (202, np.float64(0.22749758188781843)), (203, np.float64(0.39581591337445343)), (204, np.float64(0.46563893539088363)), (205, np.float64(1.0000000000000002)), (206, np.float64(0.46563893539088363)), (207, np.float64(0.3011575600364142)), (208, np.float64(0.19780286479296233)), (209, np.float64(0.0)), (210, np.float64(0.9290453925250155)), (211, np.float64(0.5379003219367802)), (212, np.float64(0.0)), (213, np.float64(0.42303688728381483)), (214, np.float64(0.5751843236377825)), (215, np.float64(0.1751994770502811)), (216, np.float64(0.3011575600364142)), (217, np.float64(0.5583761827288268)), (218, np.float64(0.7510653318211786)), (219, np.float64(0.21611604056764613)), (220, np.float64(0.7639060605607628)), (221, np.float64(0.8777323147245603)), (222, np.float64(0.8777323147245603)), (223, np.float64(0.7431543681273995)), (224, np.float64(0.0)), (225, np.float64(0.3213568438310123)), (226, np.float64(0.8499209801115732)), (227, np.float64(1.0000000000000002)), (228, np.float64(1.0000000000000002)), (229, np.float64(0.0)), (230, np.float64(0.8617951432750772)), (231, np.float64(1.0000000000000002)), (232, np.float64(0.18903845008879386)), (233, np.float64(0.14688699329647817)), (234, np.float64(0.5751843236377825)), (235, np.float64(0.8263071010186243)), (236, np.float64(0.6498470442549847)), (237, np.float64(0.5379003219367802)), (238, np.float64(0.432782720250225)), (239, np.float64(1.0000000000000002)), (240, np.float64(0.3723872764105476)), (241, np.float64(0.2677301804951162)), (242, np.float64(0.5379003219367802)), (243, np.float64(0.14688699329647817)), (244, np.float64(0.0)), (245, np.float64(0.23654000895286165)), (246, np.float64(0.8326987906296466)), (247, np.float64(0.0)), (248, np.float64(0.0)), (249, np.float64(0.23583841337504233)), (250, np.float64(0.19688265911626648)), (251, np.float64(0.18903845008879386)), (252, np.float64(0.0)), (253, np.float64(0.9090859958717425)), (254, np.float64(0.8314692706543022)), (255, np.float64(0.0)), (256, np.float64(0.5379003219367802)), (257, np.float64(1.0000000000000002)), (258, np.float64(0.3011575600364142)), (259, np.float64(0.46563893539088363)), (260, np.float64(0.5583761827288268)), (261, np.float64(0.0)), (262, np.float64(0.0)), (263, np.float64(0.8777323147245603)), (264, np.float64(0.3161799037806855)), (265, np.float64(0.0)), (266, np.float64(0.0)), (267, np.float64(0.8641819623026593)), (268, np.float64(0.9290453925250155)), (269, np.float64(0.0)), (270, np.float64(0.22749758188781843)), (271, np.float64(0.5751843236377825)), (272, np.float64(0.6722587486419285)), (273, np.float64(0.24469295275538902)), (274, np.float64(0.5379003219367802)), (275, np.float64(0.9290453925250155)), (276, np.float64(0.7993144266420142)), (277, np.float64(0.0)), (278, np.float64(0.0)), (279, np.float64(0.3011575600364142)), (280, np.float64(0.0)), (281, np.float64(0.0)), (282, np.float64(0.23583841337504233)), (283, np.float64(0.1934934160699502)), (284, np.float64(0.0)), (285, np.float64(0.0)), (286, np.float64(0.18903845008879386)), (287, np.float64(0.5379003219367802)), (288, np.float64(0.4144801255275111)), (289, np.float64(0.3927046456875748)), (290, np.float64(0.0)), (291, np.float64(0.1970962638552968)), (292, np.float64(0.2359921521669648)), (293, np.float64(0.15796958307043368)), (294, np.float64(0.2677301804951162)), (295, np.float64(0.0)), (296, np.float64(0.19780286479296233)), (297, np.float64(0.9290453925250155)), (298, np.float64(0.7211588913088163)), (299, np.float64(0.1970962638552968)), (300, np.float64(0.2667141124411731)), (301, np.float64(0.6349398678600585)), (302, np.float64(0.5912621929015838)), (303, np.float64(0.8503380725802234)), (304, np.float64(0.5379003219367802)), (305, np.float64(0.22749758188781843)), (306, np.float64(0.2297615049804784)), (307, np.float64(0.37100482834651527)), (308, np.float64(0.8173023338214698)), (309, np.float64(0.36009479425971075)), (310, np.float64(0.0)), (311, np.float64(0.0)), (312, np.float64(0.46563893539088363)), (313, np.float64(0.0)), (314, np.float64(0.0)), (315, np.float64(0.8173023338214698)), (316, np.float64(0.1517537918780586)), (317, np.float64(0.0)), (318, np.float64(0.8151295312847748)), (319, np.float64(0.0)), (320, np.float64(0.21611604056764613)), (321, np.float64(0.21611604056764613)), (322, np.float64(0.0)), (323, np.float64(0.0)), (324, np.float64(0.0)), (325, np.float64(0.46563893539088363)), (326, np.float64(0.46563893539088363)), (327, np.float64(0.30249527459983805)), (328, np.float64(0.42303688728381483)), (329, np.float64(0.5386251654385774)), (330, np.float64(0.9290453925250155)), (331, np.float64(0.7639060605607628)), (332, np.float64(0.24469295275538902)), (333, np.float64(0.3011575600364142)), (334, np.float64(0.0)), (335, np.float64(0.37050659018133075)), (336, np.float64(0.6349398678600585)), (337, np.float64(0.24469295275538902)), (338, np.float64(0.9456976068460856)), (339, np.float64(0.0)), (340, np.float64(0.3011575600364142)), (341, np.float64(0.2074194505173765)), (342, np.float64(0.0)), (343, np.float64(0.0)), (344, np.float64(0.21611604056764613)), (345, np.float64(0.2595731540023543)), (346, np.float64(0.4180968555740999)), (347, np.float64(0.0)), (348, np.float64(0.22840121087133897)), (349, np.float64(0.3213568438310123)), (350, np.float64(0.0)), (351, np.float64(0.3011575600364142)), (352, np.float64(0.39581591337445343)), (353, np.float64(0.0)), (354, np.float64(0.651880282786496)), (355, np.float64(0.21611604056764613)), (356, np.float64(0.0)), (357, np.float64(0.3213568438310123)), (358, np.float64(0.8173023338214698)), (359, np.float64(0.8641819623026593)), (360, np.float64(0.0)), (361, np.float64(0.5771844754358084)), (362, np.float64(0.7993144266420142)), (363, np.float64(0.0)), (364, np.float64(0.24469295275538902)), (365, np.float64(0.42303688728381483)), (366, np.float64(0.3750370120136373)), (367, np.float64(0.855188933634821)), (368, np.float64(0.22749758188781843)), (369, np.float64(0.7725615601373472)), (370, np.float64(0.21611604056764613)), (371, np.float64(0.7058564542082726)), (372, np.float64(0.7639060605607628)), (373, np.float64(0.0)), (374, np.float64(0.0)), (375, np.float64(0.46563893539088363)), (376, np.float64(0.0)), (377, np.float64(0.1911659918442979)), (378, np.float64(0.0)), (379, np.float64(0.5751843236377825)), (380, np.float64(0.40731910906486923)), (381, np.float64(0.0)), (382, np.float64(0.2677301804951162)), (383, np.float64(0.3011575600364142)), (384, np.float64(0.0)), (385, np.float64(0.5379003219367802)), (386, np.float64(0.0)), (387, np.float64(0.0)), (388, np.float64(0.3011575600364142)), (389, np.float64(0.0)), (390, np.float64(0.3213568438310123)), (391, np.float64(0.0)), (392, np.float64(0.2677301804951162)), (393, np.float64(0.0)), (394, np.float64(0.0)), (395, np.float64(0.22840121087133897)), (396, np.float64(1.0000000000000002)), (397, np.float64(0.0)), (398, np.float64(0.4889373677550547)), (399, np.float64(0.3723872764105476)), (400, np.float64(0.0)), (401, np.float64(0.21201439810090789)), (402, np.float64(0.0)), (403, np.float64(0.0)), (404, np.float64(0.2677301804951162)), (405, np.float64(0.0)), (406, np.float64(0.7037275846552724)), (407, np.float64(0.5583761827288268)), (408, np.float64(0.9290453925250155)), (409, np.float64(0.5295777764751498)), (410, np.float64(0.26833091731548425)), (411, np.float64(0.8777323147245603)), (412, np.float64(0.0)), (413, np.float64(0.0)), (414, np.float64(0.0)), (415, np.float64(0.7630988824097306)), (416, np.float64(0.7630988824097306)), (417, np.float64(0.0)), (418, np.float64(0.7725615601373472)), (419, np.float64(0.0)), (420, np.float64(0.5379003219367802)), (421, np.float64(0.5379003219367802)), (422, np.float64(0.7630988824097306)), (423, np.float64(0.0)), (424, np.float64(0.24068395608755438)), (425, np.float64(0.0)), (426, np.float64(0.0)), (427, np.float64(0.0)), (428, np.float64(0.253049481994157)), (429, np.float64(0.2074194505173765)), (430, np.float64(0.0)), (431, np.float64(0.0)), (432, np.float64(0.0)), (433, np.float64(0.258651191609442)), (434, np.float64(0.0)), (435, np.float64(0.0)), (436, np.float64(0.0)), (437, np.float64(0.48801000778696574)), (438, np.float64(0.7095545072308225)), (439, np.float64(0.0)), (440, np.float64(0.0)), (441, np.float64(0.0)), (442, np.float64(0.22749758188781843)), (443, np.float64(0.2050469081351088)), (444, np.float64(0.0)), (445, np.float64(0.7993144266420142)), (446, np.float64(0.5911787638404287)), (447, np.float64(0.0)), (448, np.float64(0.0)), (449, np.float64(0.15648091321432042)), (450, np.float64(0.6498470442549847)), (451, np.float64(0.1934934160699502)), (452, np.float64(0.1865883293065326)), (453, np.float64(0.47183547207891907)), (454, np.float64(0.21611604056764613)), (455, np.float64(0.16748037264232096)), (456, np.float64(0.0)), (457, np.float64(0.777195571939715)), (458, np.float64(0.0)), (459, np.float64(0.0)), (460, np.float64(0.0)), (461, np.float64(1.0000000000000002)), (462, np.float64(0.3927046456875748)), (463, np.float64(0.22749758188781843)), (464, np.float64(0.6349398678600585)), (465, np.float64(0.0)), (466, np.float64(0.0)), (467, np.float64(0.397945262512527)), (468, np.float64(0.5793186643228521)), (469, np.float64(0.5751843236377825)), (470, np.float64(0.7993144266420142)), (471, np.float64(0.0)), (472, np.float64(0.5379003219367802)), (473, np.float64(0.22840121087133897)), (474, np.float64(0.6572530917633163)), (475, np.float64(0.0)), (476, np.float64(0.0)), (477, np.float64(1.0000000000000002)), (478, np.float64(0.40731910906486923)), (479, np.float64(0.22024831329242428)), (480, np.float64(0.46563893539088363)), (481, np.float64(0.7993144266420142)), (482, np.float64(0.1970962638552968)), (483, np.float64(0.0)), (484, np.float64(0.9290453925250155)), (485, np.float64(0.3633645870352965)), (486, np.float64(0.0)), (487, np.float64(0.0)), (488, np.float64(0.0)), (489, np.float64(1.0000000000000002)), (490, np.float64(0.0)), (491, np.float64(0.0)), (492, np.float64(0.23189286647386853)), (493, np.float64(0.0)), (494, np.float64(0.22749758188781843)), (495, np.float64(0.22378001248742024)), (496, np.float64(0.6867024616863745)), (497, np.float64(0.35329921962559263)), (498, np.float64(0.0)), (499, np.float64(0.682169876903219)), (500, np.float64(0.0)), (501, np.float64(1.0000000000000002)), (502, np.float64(1.0000000000000002)), (503, np.float64(0.0)), (504, np.float64(0.7639060605607628)), (505, np.float64(1.0000000000000002)), (506, np.float64(0.22749758188781843)), (507, np.float64(0.5379003219367802)), (508, np.float64(0.21611604056764613)), (509, np.float64(0.0)), (510, np.float64(0.0)), (511, np.float64(0.0)), (512, np.float64(0.4436960596167126)), (513, np.float64(0.0)), (514, np.float64(0.0)), (515, np.float64(0.0)), (516, np.float64(0.0)), (517, np.float64(0.5379003219367802)), (518, np.float64(0.0)), (519, np.float64(0.16759241849897258)), (520, np.float64(0.0)), (521, np.float64(0.0)), (522, np.float64(0.1779591445578572)), (523, np.float64(0.1865883293065326)), (524, np.float64(0.21379662889765477)), (525, np.float64(0.5583761827288268)), (526, np.float64(0.0)), (527, np.float64(0.0)), (528, np.float64(0.20036432136615503)), (529, np.float64(0.48184680644110545)), (530, np.float64(0.0)), (531, np.float64(0.22256473618580028)), (532, np.float64(0.0)), (533, np.float64(0.7493600690153979)), (534, np.float64(0.4889373677550547)), (535, np.float64(0.6572530917633163)), (536, np.float64(0.6705809051473737)), (537, np.float64(0.3477146109308615)), (538, np.float64(0.5001036536817958)), (539, np.float64(0.6498470442549847)), (540, np.float64(0.21611604056764613)), (541, np.float64(0.21069291904868057)), (542, np.float64(0.0)), (543, np.float64(0.7725615601373472)), (544, np.float64(0.0)), (545, np.float64(0.3077655094170494)), (546, np.float64(0.0)), (547, np.float64(0.2677301804951162)), (548, np.float64(0.0)), (549, np.float64(0.0)), (550, np.float64(0.14688699329647817)), (551, np.float64(0.0)), (552, np.float64(0.0)), (553, np.float64(0.0)), (554, np.float64(0.41660851180680714)), (555, np.float64(0.2911061909310497)), (556, np.float64(0.0)), (557, np.float64(0.0)), (558, np.float64(0.5386251654385774)), (559, np.float64(0.18903845008879386)), (560, np.float64(0.21611604056764613)), (561, np.float64(0.0)), (562, np.float64(0.5379003219367802)), (563, np.float64(0.21611604056764613)), (564, np.float64(0.3011575600364142)), (565, np.float64(0.17153053794800407)), (566, np.float64(0.2297615049804784)), (567, np.float64(0.3011575600364142)), (568, np.float64(0.22749758188781843)), (569, np.float64(0.497956281255

In [108]:
len(similarity_score)

4666

In [109]:
sorted_similar_movies = sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(4, np.float64(1.0000000000000002)), (7, np.float64(1.0000000000000002)), (16, np.float64(1.0000000000000002)), (26, np.float64(1.0000000000000002)), (31, np.float64(1.0000000000000002)), (35, np.float64(1.0000000000000002)), (36, np.float64(1.0000000000000002)), (39, np.float64(1.0000000000000002)), (47, np.float64(1.0000000000000002)), (51, np.float64(1.0000000000000002)), (52, np.float64(1.0000000000000002)), (56, np.float64(1.0000000000000002)), (67, np.float64(1.0000000000000002)), (78, np.float64(1.0000000000000002)), (84, np.float64(1.0000000000000002)), (90, np.float64(1.0000000000000002)), (93, np.float64(1.0000000000000002)), (99, np.float64(1.0000000000000002)), (100, np.float64(1.0000000000000002)), (109, np.float64(1.0000000000000002)), (156, np.float64(1.0000000000000002)), (167, np.float64(1.0000000000000002)), (172, np.float64(1.0000000000000002)), (180, np.float64(1.0000000000000002)), (181, np.float64(1.0000000000000002)), (191, np.float64(1.0000000000000002)), (205, np.float64(1.0000000000000002)), (227, np.float64(1.0000000000000002)), (228, np.float64(1.0000000000000002)), (231, np.float64(1.0000000000000002)), (239, np.float64(1.0000000000000002)), (257, np.float64(1.0000000000000002)), (396, np.float64(1.0000000000000002)), (461, np.float64(1.0000000000000002)), (477, np.float64(1.0000000000000002)), (489, np.float64(1.0000000000000002)), (501, np.float64(1.0000000000000002)), (502, np.float64(1.0000000000000002)), (505, np.float64(1.0000000000000002)), (571, np.float64(1.0000000000000002)), (1067, np.float64(1.0000000000000002)), (1470, np.float64(1.0000000000000002)), (1961, np.float64(1.0000000000000002)), (2330, np.float64(1.0000000000000002)), (2391, np.float64(1.0000000000000002)), (2402, np.float64(1.0000000000000002)), (2450, np.float64(1.0000000000000002)), (2854, np.float64(1.0000000000000002)), (2936, np.float64(1.0000000000000002)), (3238, np.float64(1.0000000000000002)), (3951, np.float64(1.0000000000000002)), (4022, np.float64(1.0000000000000002)), (148, np.float64(0.9456976068460856)), (338, np.float64(0.9456976068460856)), (27, np.float64(0.9290453925250155)), (28, np.float64(0.9290453925250155)), (33, np.float64(0.9290453925250155)), (41, np.float64(0.9290453925250155)), (75, np.float64(0.9290453925250155)), (106, np.float64(0.9290453925250155)), (120, np.float64(0.9290453925250155)), (121, np.float64(0.9290453925250155)), (123, np.float64(0.9290453925250155)), (125, np.float64(0.9290453925250155)), (147, np.float64(0.9290453925250155)), (164, np.float64(0.9290453925250155)), (201, np.float64(0.9290453925250155)), (210, np.float64(0.9290453925250155)), (268, np.float64(0.9290453925250155)), (275, np.float64(0.9290453925250155)), (297, np.float64(0.9290453925250155)), (330, np.float64(0.9290453925250155)), (408, np.float64(0.9290453925250155)), (484, np.float64(0.9290453925250155)), (575, np.float64(0.9290453925250155)), (581, np.float64(0.9290453925250155)), (746, np.float64(0.9290453925250155)), (928, np.float64(0.9290453925250155)), (965, np.float64(0.9290453925250155)), (990, np.float64(0.9290453925250155)), (1022, np.float64(0.9290453925250155)), (1071, np.float64(0.9290453925250155)), (1186, np.float64(0.9290453925250155)), (1278, np.float64(0.9290453925250155)), (1287, np.float64(0.9290453925250155)), (1509, np.float64(0.9290453925250155)), (1561, np.float64(0.9290453925250155)), (1724, np.float64(0.9290453925250155)), (2034, np.float64(0.9290453925250155)), (2276, np.float64(0.9290453925250155)), (2286, np.float64(0.9290453925250155)), (2764, np.float64(0.9290453925250155)), (3984, np.float64(0.9290453925250155)), (4542, np.float64(0.9290453925250155)), (2400, np.float64(0.9105010416295487)), (82, np.float64(0.9095579740208651)), (3282, np.float64(0.9095579740208651)), (253, np.float64(0.9090859958717425)), (668, np.float64(0.9090859958717425)), (1309, np.float64(0.9090859958717425)), (1931, np.float64(0.9090859958717425)), (3333, np.float64(0.9090859958717425)), (73, np.float64(0.8777323147245603)), (221, np.float64(0.8777323147245603)), (222, np.float64(0.8777323147245603)), (263, np.float64(0.8777323147245603)), (411, np.float64(0.8777323147245603)), (576, np.float64(0.8777323147245603)), (628, np.float64(0.8777323147245603)), (1139, np.float64(0.8777323147245603)), (1255, np.float64(0.8777323147245603)), (1586, np.float64(0.8777323147245603)), (1627, np.float64(0.8777323147245603)), (3387, np.float64(0.8777323147245603)), (3921, np.float64(0.8777323147245603)), (4079, np.float64(0.8777323147245603)), (4089, np.float64(0.8777323147245603)), (4095, np.float64(0.8777323147245603)), (789, np.float64(0.8761137214875123)), (1081, np.float64(0.8761137214875123)), (4241, np.float64(0.8761137214875123)), (2097, np.float64(0.8756132748765459)), (94, np.float64(0.8641819623026593)), (267, np.float64(0.8641819623026593)), (359, np.float64(0.8641819623026593)), (2333, np.float64(0.8641819623026593)), (3490, np.float64(0.8641819623026593)), (4229, np.float64(0.8641819623026593)), (0, np.float64(0.8617951432750772)), (10, np.float64(0.8617951432750772)), (14, np.float64(0.8617951432750772)), (46, np.float64(0.8617951432750772)), (60, np.float64(0.8617951432750772)), (230, np.float64(0.8617951432750772)), (803, np.float64(0.8617951432750772)), (859, np.float64(0.8617951432750772)), (3420, np.float64(0.8617951432750772)), (367, np.float64(0.855188933634821)), (961, np.float64(0.855188933634821)), (303, np.float64(0.8503380725802234)), (1202, np.float64(0.8503380725802234)), (1327, np.float64(0.8503380725802234)), (2932, np.float64(0.8503380725802234)), (3948, np.float64(0.8503380725802234)), (226, np.float64(0.8499209801115732)), (2014, np.float64(0.8426045406471736)), (1032, np.float64(0.8384637986268226)), (1141, np.float64(0.8384637986268226)), (1801, np.float64(0.8384637986268226)), (183, np.float64(0.8326987906296466)), (198, np.float64(0.8326987906296466)), (246, np.float64(0.8326987906296466)), (163, np.float64(0.8314692706543022)), (254, np.float64(0.8314692706543022)), (1270, np.float64(0.8314692706543022)), (647, np.float64(0.8272138659127308)), (1846, np.float64(0.8272138659127308)), (235, np.float64(0.8263071010186243)), (612, np.float64(0.8263071010186243)), (1176, np.float64(0.8263071010186243)), (1280, np.float64(0.8263071010186243)), (1906, np.float64(0.8263071010186243)), (909, np.float64(0.8240975830833568)), (911, np.float64(0.8240975830833568)), (18, np.float64(0.8173023338214698)), (308, np.float64(0.8173023338214698)), (315, np.float64(0.8173023338214698)), (358, np.float64(0.8173023338214698)), (1409, np.float64(0.8173023338214698)), (2123, np.float64(0.8173023338214698)), (2732, np.float64(0.8173023338214698)), (3122, np.float64(0.8173023338214698)), (4296, np.float64(0.8173023338214698)), (4342, np.float64(0.8173023338214698)), (4497, np.float64(0.8173023338214698)), (318, np.float64(0.8151295312847748)), (1215, np.float64(0.8151295312847748)), (1371, np.float64(0.8151295312847748)), (1629, np.float64(0.8151295312847748)), (2710, np.float64(0.8132507412904362)), (95, np.float64(0.8050599033877955)), (601, np.float64(0.8050599033877955)), (723, np.float64(0.8050599033877955)), (43, np.float64(0.7993144266420142)), (92, np.float64(0.7993144266420142)), (276, np.float64(0.7993144266420142)), (362, np.float64(0.7993144266420142)), (445, np.float64(0.7993144266420142)), (470, np.float64(0.7993144266420142)), (481, np.float64(0.7993144266420142)), (595, np.float64(0.7993144266420142)), (651, np.float64(0.7993144266420142)), (709, np.float64(0.7993144266420142)), (983, np.float64(0.7993144266420142)), (991, np.float64(0.7993144266420142)), (1257, np.float64(0.7993144266420142)), (1302, np.float64(0.7993144266420142)), (1380, np.float64(0.7993144266420142)), (1393, np.float64(0.7993144266420142)), (1471, np.float64(0.7993144266420142)), (1546, np.float64(0.7993144266420142)), (1610, np.float64(0.7993144266420142)), (1800, np.float64(0.7993144266420142)), (1966, np.float64(0.7993144266420142)), (2015, np.float64(0.7993144266420142)), (2165, np.float64(0.7993144266420142)), (2219, np.float64(0.7993144266420142)), (2279, np.float64(0.7993144266420142)), (2444, np.float64(0.7993144266420142)), (2595, np.float64(0.7993144266420142)), (2816, np.float64(0.7993144266420142)), (3367, np.float64(0.7993144266420142)), (3903, np.float64(0.7918919998528471)), (71, np.float64(0.7914700916020292)), (1449, np.float64(0.7797578536574781)), (1177, np.float64(0.7786737924861212)), (2131, np.float64(0.7786737924861212)), (4541, np.float64(0.7777080189796074)), (457, np.float64(0.777195571939715)), (949, np.float64(0.777195571939715)), (2707, np.float64(0.777195571939715)), (63, np.float64(0.7725615601373472)), (369, np.float64(0.7725615601373472)), (418, np.float64(0.7725615601373472)), (543, np.float64(0.7725615601373472)), (1396, np.float64(0.7725615601373472)), (1532, np.float64(0.7725615601373472)), (2844, np.float64(0.7725615601373472)), (2876, np.float64(0.7725615601373472)), (2965, np.float64(0.7725615601373472)), (3150, np.float64(0.7725615601373472)), (3868, np.float64(0.7725615601373472)), (4154, np.float64(0.7725615601373472)), (4175, np.float64(0.7725615601373472)), (4607, np.float64(0.7725615601373472)), (81, np.float64(0.7639060605607628)), (220, np.float64(0.7639060605607628)), (331, np.float64(0.7639060605607628)), (372, np.float64(0.7639060605607628)), (504, np.float64(0.7639060605607628)), (840, np.float64(0.7639060605607628)), (918, np.float64(0.7639060605607628)), (3590, np.float64(0.7639060605607628)), (4600, np.float64(0.7639060605607628)), (415, np.float64(0.7630988824097306)), (416, np.float64(0.7630988824097306)), (422, np.float64(0.7630988824097306)), (997, np.float64(0.7627041648860131)), (1340, np.float64(0.7561716094682507)), (726, np.float64(0.7528758929206307)), (4319, np.float64(0.7528758929206307)), (218, np.float64(0.7510653318211786)), (1349, np.float64(0.7510653318211786)), (2907, np.float64(0.7510653318211786)), (3812, np.float64(0.7510653318211786)), (533, np.float64(0.7493600690153979)), (650, np.float64(0.7436699398113524)), (731, np.float64(0.7436699398113524)), (828, np.float64(0.7436699398113524)), (945, np.float64(0.7436699398113524)), (1058, np.float64(0.7436699398113524)), (1358, np.float64(0.7436699398113524)), (1376, np.float64(0.7436699398113524)), (1709, np.float64(0.7436699398113524)), (3899, np.float64(0.7436699398113524)), (4224, np.float64(0.7436699398113524)), (223, np.float64(0.7431543681273995)), (166, np.float64(0.7406437932326532)), (3144, np.float64(0.7406437932326532)), (769, np.float64(0.7395227105029327)), (1056, np.float64(0.7395227105029327)), (1138, np.float64(0.7395227105029327)), (1151, np.float64(0.7395227105029327)), (2247, np.float64(0.7395227105029327)), (69, np.float64(0.7315159960267821)), (719, np.float64(0.7289924163206523)), (1589, np.float64(0.7289924163206523)), (1776, np.float64(0.7289924163206523)), (2548, np.float64(0.7289924163206523)), (1768, np.float64(0.7278318759344726)), (298, np.float64(0.7211588913088163)), (1004, np.float64(0.7211588913088163)), (1838, np.float64(0.7211588913088163)), (2055, np.float64(0.7211588913088163)), (2594, np.float64(0.7211588913088163)), (2704, np.float64(0.7211588913088163)), (3093, np.float64(0.7211588913088163)), (3546, np.float64(0.7211588913088163)), (4276, np.float64(0.7211588913088163)), (4294, np.float64(0.7211588913088163)), (4524, np.float64(0.7211588913088163)), (4558, np.float64(0.7211588913088163)), (4569, np.float64(0.7211588913088163)), (161, np.float64(0.716934294431677)), (438, np.float64(0.7095545072308225)), (1496, np.float64(0.7095545072308225)), (1602, np.float64(0.7095545072308225)), (1689, np.float64(0.7095545072308225)), (371, np.float64(0.7058564542082726)), (1983, np.float64(0.7058564542082726)), (2440, np.float64(0.7058564542082726)), (2561, np.float64(0.7058564542082726)), (3457, np.float64(0.7058564542082726)), (3898, np.float64(0.7058564542082726)), (4060, np.float64(0.7058564542082726)), (4445, np.float64(0.7058353650297917)), (406, np.float64(0.7037275846552724)), (1462, np.float64(0.694151715077483)), (2052, np.float64(0.694151715077483)), (2361, np.float64(0.694151715077483)), (3072, np.float64(0.694151715077483)), (3096, np.float64(0.694151715077483)), (3293, np.float64(0.694151715077483)), (3667, np.float64(0.694151715077483)), (3833, np.float64(0.694151715077483)), (1910, np.float64(0.6932492651526513)), (2347, np.float64(0.6899253521615871)), (4375, np.float64(0.6874614996606214)), (496, np.float64(0.6867024616863745)), (714, np.float64(0.6867024616863745)), (1260, np.float64(0.6867024616863745)), (1876, np.float64(0.6867024616863745)), (2608, np.float64(0.6867024616863745)), (2695, np.float64(0.6867024616863745)), (2766, np.float64(0.6867024616863745)), (2813, np.float64(0.6867024616863745)), (3355, np.float64(0.6867024616863745)), (3913, np.float64(0.6867024616863745)), (4624, np.float64(0.6867024616863745)), (4653, np.float64(0.6867024616863745)), (499, np.float64(0.682169876903219)), (1097, np.float64(0.682169876903219)), (1324, np.float64(0.682169876903219)), (654, np.float64(0.6799740441746844)), (2908, np.float64(0.6799740441746844)), (773, np.float64(0.6764689776340082)), (4166, np.float64(0.675059158357534)), (272, np.float64(0.6722587486419285)), (1446, np.float64(0.6722587486419285)), (86, np.float64(0.6714186581201941)), (45, np.float64(0.6705809051473737)), (114, np.float64(0.6705809051473737)), (536, np.float64(0.6705809051473737)), (3713, np.float64(0.6705809051473737)), (2811, np.float64(0.6660083475051459)), (2741, np.float64(0.6649730392191602)), (1731, np.float64(0.6630824841554329)), (474, np.float64(0.6572530917633163)), (535, np.float64(0.6572530917633163)), (1074, np.float64(0.6543128862644022)), (2095, np.float64(0.6543128862644022)), (2775, np.float64(0.6543128862644022)), (66, np.float64(0.651880282786496)), (354, np.float64(0.651880282786496)), (236, np.float64(0.6498470442549847)), (450, np.float64(0.6498470442549847)), (539, np.float64(0.6498470442549847)), (711, np.float64(0.6498470442549847)), (1098, np.float64(0.6498470442549847)), (1453, np.float64(0.6498470442549847)), (1699, np.float64(0.6498470442549847)), (2592, np.float64(0.6498470442549847)), (2678, np.float64(0.6498470442549847)), (2773, np.float64(0.6498470442549847)), (3478, np.float64(0.6498470442549847)), (3941, np.float64(0.6498470442549847)), (4428, np.float64(0.6498470442549847)), (4563, np.float64(0.6498470442549847)), (4630, np.float64(0.6498470442549847)), (4660, np.float64(0.6498470442549847)), (920, np.float64(0.6461737358283398)), (21, np.float64(0.6349398678600585)), (53, np.float64(0.6349398678600585)), (61, np.float64(0.6349398678600585)), (74, np.float64(0.6349398678600585)), (301, np.float64(0.6349398678600585)), (336, np.float64(0.6349398678600585)), (464, np.float64(0.6349398678600585)), (604, np.float64(0.6349398678600585)), (633, np.float64(0.6349398678600585)), (995, np.float64(0.6349398678600585)), (1077, np.float64(0.6349398678600585)), (1672, np.float64(0.6349398678600585)), (2053, np.float64(0.6349398678600585)), (3643, np.float64(0.6349398678600585)), (4213, np.float64(0.6349398678600585)), (3304, np.float64(0.6329122866647169)), (1968, np.float64(0.6313410345990046)), (2120, np.float64(0.6313410345990046)), (2586, np.float64(0.6313410345990046)), (4321, np.float64(0.6313410345990046)), (2345, np.float64(0.6292571203704532)), (2649, np.float64(0.6292571203704532)), (2790, np.float64(0.6292571203704532)), (3085, np.float64(0.6292571203704532)), (3654, np.float64(0.6292571203704532)), (3799, np.float64(0.6292571203704532)), (4035, np.float64(0.6292571203704532)), (4183, np.float64(0.6292571203704532)), (4354, np.float64(0.6292571203704532)), (4403, np.float64(0.6292571203704532)), (4611, np.float64(0.6292571203704532)), (745, np.float64(0.6291673790232285)), (1183, np.float64(0.6291673790232285)), (2546, np.float64(0.6291673790232285)), (4478, np.float64(0.6287368109823078)), (2338, np.float64(0.6224603409800503)), (1262, np.float64(0.6216182706037949)), (3980, np.float64(0.6209972312965775)), (667, np.float64(0.6185661607949731)), (2228, np.float64(0.6137449248813878)), (759, np.float64(0.6132475357971394)), (1198, np.float64(0.6132475357971394)), (2125, np.float64(0.6132475357971394)), (889, np.float64(0.6078340746713655)), (666, np.float64(0.6076118397001721)), (2283, np.float64(0.6076118397001721)), (1256, np.float64(0.6060170975730257)), (1736, np.float64(0.6025446557118024)), (2825, np.float64(0.6005342845319505)), (194, np.float64(0.5962771999364336)), (988, np.float64(0.5933420553862685)), (2996, np.float64(0.5933420553862685)), (4358, np.float64(0.5933420553862685)), (2467, np.float64(0.5916112268621042)), (3101, np.float64(0.5916112268621042)), (3552, np.float64(0.5916112268621042)), (4594, np.float64(0.5916112268621042)), (302, np.float64(0.5912621929015838)), (966, np.float64(0.5912621929015838)), (1956, np.float64(0.5912621929015838)), (446, np.float64(0.5911787638404287)), (1041, np.float64(0.5911787638404287)), (2368, np.float64(0.5911787638404287)), (2698, np.float64(0.5911787638404287)), (2865, np.float64(0.5911787638404287)), (3817, np.float64(0.5911787638404287)), (4064, np.float64(0.5876891599756509)), (4295, np.float64(0.5876891599756509)), (3255, np.float64(0.5818286855680077)), (3931, np.float64(0.5816337627849809)), (766, np.float64(0.5801963967499492)), (1360, np.float64(0.5801963967499492)), (1619, np.float64(0.5801963967499492)), (2044, np.float64(0.5801963967499492)), (2517, np.float64(0.5801963967499492)), (2703, np.float64(0.5801963967499492)), (2780, np.float64(0.5801963967499492)), (2905, np.float64(0.5801963967499492)), (2943, np.float64(0.5801963967499492)), (2955, np.float64(0.5801963967499492)), (3175, np.float64(0.5801963967499492)), (3526, np.float64(0.5801963967499492)), (3574, np.float64(0.5801963967499492)), (3578, np.float64(0.5801963967499492)), (3808, np.float64(0.5801963967499492)), (3860, np.float64(0.5801963967499492)), (3976, np.float64(0.5801963967499492)), (4464, np.float64(0.5801963967499492)), (468, np.float64(0.5793186643228521)), (1073, np.float64(0.5793186643228521)), (1244, np.float64(0.5793186643228521)), (1259, np.float64(0.5793186643228521)), (1620, np.float64(0.5793186643228521)), (3318, np.float64(0.5793186643228521)), (3718, np.float64(0.5793186643228521)), (361, np.float64(0.5771844754358084)), (3013, np.float64(0.5771844754358084)), (3564, np.float64(0.5771844754358084)), (4582, np.float64(0.5771844754358084)), (3088, np.float64(0.5760906134386358)), (3139, np.float64(0.5760906134386358)), (24, np.float64(0.5751843236377825)), (155, np.float64(0.5751843236377825)), (214, np.float64(0.5751843236377825)), (234, np.float64(0.5751843236377825)), (271, np.float64(0.5751843236377825)), (379, np.float64(0.5751843236377825)), (469, np.float64(0.5751843236377825)), (1224, np.float64(0.5751843236377825)), (1282, np.float64(0.5751843236377825)), (1361, np.float64(0.5751843236377825)), (2464, np.float64(0.5751843236377825)), (2599, np.float64(0.5751843236377825)), (3159, np.float64(0.5751843236377825)), (3166, np.float64(0.5751843236377825)), (3446, np.float64(0.5751843236377825)), (4047, np.float64(0.5751843236377825)), (4050, np.float64(0.5751843236377825)), (4387, np.float64(0.5751843236377825)), (4476, np.float64(0.5751843236377825)), (4495, np.float64(0.5751843236377825)), (1513, np.float64(0.570776334208531)), (743, np.float64(0.567170940832156)), (4340, np.float64(0.567170940832156)), (4125, np.float64(0.5630986498210627)), (620, np.float64(0.5590584115838899)), (897, np.float64(0.5590584115838899)), (1486, np.float64(0.5590584115838899)), (1782, np.float64(0.5590584115838899)), (2442, np.float64(0.5590584115838899)), (2843, np.float64(0.5590584115838899)), (2959, np.float64(0.5590584115838899)), (3140, np.float64(0.5590584115838899)), (3649, np.float64(0.5590584115838899)), (4438, np.float64(0.5590584115838899)), (4512, np.float64(0.5590584115838899)), (21

In [123]:
for movie in sorted_similar_movies:
    movie_index = movie[0]
    score = movie[1]

    title = df.iloc[movie_index]["title"]
    genre = df.iloc[movie_index]["genres"]

    print("Title:", title)
    print("Genre:", genre)
    print("Similarity:", round(score, 2))
    print("--------------------")

Title: John Carter
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Avengers: Age of Ultron
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: The Avengers
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Captain America: Civil War
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Iron Man 3
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Transformers: Revenge of the Fallen
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Transformers: Age of Extinction
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: TRON: Legacy
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Star Trek Into Darkness
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Pacific Rim
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: Transformers: Dark of the Moon
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: Star Trek Beyond
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Iron Man
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: Iron Man 2
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Captain America: The Winter Soldier
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Independence Day: Resurgence
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Guardians of the Galaxy
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: X-Men: First Class
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: The Hunger Games: Mockingjay - Part 2
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Transformers
Genre: Adventure Science Fiction Action
Similarity: 1.0
--------------------
Title: Star Trek
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Captain America: The First Avenger
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: The Incredible Hulk
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Ant-Man
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: The Hunger Games: Catching Fire
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: After Earth
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Total Recall
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Star Wars: Episode III - Revenge of the Sith
Genre: Science Fiction Adventure Action
Similarity: 1.0
--------------------
Title: Star Wars: Episode II - Attack of the Clones
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Star Wars: Episode I - The Phantom Menace
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Fantastic Four
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Ender's Game
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Divergent
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: The Time Machine
Genre: Science Fiction Adventure Action
Similarity: 1.0
--------------------
Title: Timeline
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Journey 2: The Mysterious Island
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Independence Day
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: The Lost World: Jurassic Park
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: X-Men
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: AVP: Alien vs. Predator
Genre: Adventure Science Fiction Action
Similarity: 1.0
--------------------
Title: Dune
Genre: Action Science Fiction Adventure
Similarity: 1.0
--------------------
Title: Return of the Jedi
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: The Empire Strikes Back
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Megaforce
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Superman IV: The Quest for Peace
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Damnation Alley
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Steel
Genre: Science Fiction Action Adventure
Similarity: 1.0
--------------------
Title: Star Wars
Genre: Adventure Action Science Fiction
Similarity: 1.0
--------------------
Title: Mad Max Beyond Thunderdome
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: The Blood of Heroes
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: U.F.O.
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Six-String Samurai
Genre: Action Adventure Science Fiction
Similarity: 1.0
--------------------
Title: Men in Black II
Genre: Action Adventure Comedy Science Fiction
Similarity: 0.95
--------------------
Title: Men in Black
Genre: Action Adventure Comedy Science Fiction
Similarity: 0.95
--------------------
Title: Battleship
Genre: Thriller Action Adventure Science Fiction
Similarity: 0.93
--------------------
Title: Jurassic World
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: X-Men: The Last Stand
Genre: Adventure Action Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Green Lantern
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: G.I. Joe: The Rise of Cobra
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Terminator Genisys
Genre: Science Fiction Action Thriller Adventure
Similarity: 0.93
--------------------
Title: X-Men Origins: Wolverine
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: The Matrix Revolutions
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: The Matrix Reloaded
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Mad Max: Fury Road
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Armageddon
Genre: Action Thriller Science Fiction Adventure
Similarity: 0.93
--------------------
Title: G.I. Joe: Retaliation
Genre: Adventure Action Science Fiction Thriller
Similarity: 0.93
--------------------
Title: X2
Genre: Adventure Action Science Fiction Thriller
Similarity: 0.93
--------------------
Title: The Day After Tomorrow
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: The Island
Genre: Action Thriller Science Fiction Adventure
Similarity: 0.93
--------------------
Title: Planet of the Apes
Genre: Thriller Science Fiction Action Adventure
Similarity: 0.93
--------------------
Title: Starship Troopers
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Jurassic Park III
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: The Core
Genre: Action Thriller Adventure Science Fiction
Similarity: 0.93
--------------------
Title: A Sound of Thunder
Genre: Thriller Science Fiction Adventure Action
Similarity: 0.93
--------------------
Title: Star Trek: Insurrection
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: The Abyss
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Star Trek: Nemesis
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: I Am Number Four
Genre: Action Thriller Science Fiction Adventure
Similarity: 0.93
--------------------
Title: Escape from L.A.
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Street Fighter: The Legend of Chun-Li
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Star Trek: First Contact
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Babylon A.D.
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Predators
Genre: Action Science Fiction Adventure Thriller
Similarity: 0.93
--------------------
Title: Serenity
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Star Trek: Generations
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Moonraker
Genre: Action Adventure Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Star Trek V: The Final Frontier
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Star Trek VI: The Undiscovered Country
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Firefox
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Star Trek III: The Search for Spock
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Predator
Genre: Science Fiction Action Adventure Thriller
Similarity: 0.93
--------------------
Title: Star Trek II: The Wrath of Khan
Genre: Action Adventure Science Fiction Thriller
Similarity: 0.93
--------------------
Title: Mad Max 2
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Mad Max
Genre: Adventure Action Thriller Science Fiction
Similarity: 0.93
--------------------
Title: Southland Tales
Genre: Action Adventure Comedy Drama Science Fiction
Similarity: 0.91
--------------------
Title: The Lovers
Genre: Action Adventure Science Fiction Romance
Similarity: 0.91
--------------------
Title: Logan's Run
Genre: Adventure Action Romance Science Fiction
Similarity: 0.91
--------------------
Title: Allegiant
Genre: Adventure Science Fiction
Similarity: 0.91
--------------------
Title: Jurassic Park
Genre: Adventure Science Fiction
Similarity: 0.91
--------------------
Title: The 5th Wave
Genre: Adventure Science Fiction
Similarity: 0.91
--------------------
Title: Star Trek IV: The Voyage Home
Genre: Science Fiction Adventure
Similarity: 0.91
--------------------
Title: Stargate: The Ark of Truth
Genre: Adventure Science Fiction
Similarity: 0.91
--------------------
Title: Edge of Tomorrow
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: The Chronicles of Riddick
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: RoboCop
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: I, Robot
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Dredd
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Battle: Los Angeles
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: The Matrix
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Lucy
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Universal Soldier: The Return
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: The Running Man
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Wing Commander
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Escape from New York
Genre: Science Fiction Action
Similarity: 0.88
--------------------
Title: Escape from the Planet of the Apes
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Battle for the Planet of the Apes
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Independence Daysaster
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Conquest of the Planet of the Apes
Genre: Action Science Fiction
Similarity: 0.88
--------------------
Title: Resident Evil: Afterlife
Genre: Action Adventure Horror Science Fiction
Similarity: 0.88
--------------------
Title: Deep Rising
Genre: Adventure Action Horror Science Fiction
Similarity: 0.88
--------------------
Title: Gojira ni-sen mireniamu
Genre: Adventure Horror Action Science Fiction
Similarity: 0.88
--------------------
Title: The Black Hole
Genre: Adventure Family Science Fiction Action
Similarity: 0.88
--------------------
Title: Interstellar
Genre: Adventure Drama Science Fiction
Similarity: 0.86
--------------------
Title: The Martian
Genre: Drama Adventure Science Fiction
Similarity: 0.86
--------------------
Title: A.I. Artificial Intelligence
Genre: Drama Science Fiction Adventure
Similarity: 0.86
--------------------
Title: Midnight Special
Genre: Adventure Drama Science Fiction
Similarity: 0.86
--------------------
Title: 20,000 Leagues Under the Sea
Genre: Adventure Drama Science Fiction
Similarity: 0.86
--------------------
Title: Silent Running
Genre: Adventure Drama Science Fiction
Similarity: 0.86
--------------------
Title: Avatar
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: Superman Returns
Genre: Adventure Fantasy Action Science Fiction
Similarity: 0.86
--------------------
Title: Man of Steel
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: X-Men: Days of Future Past
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: Jupiter Ascending
Genre: Science Fiction Fantasy Action Adventure
Similarity: 0.86
--------------------
Title: The Wolverine
Genre: Action Science Fiction Adventure Fantasy
Similarity: 0.86
--------------------
Title: Superman
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: Superman II
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: Beastmaster 2: Through the Portal of Time
Genre: Action Adventure Fantasy Science Fiction
Similarity: 0.86
--------------------
Title: The Saint
Genre: Thriller Action Romance Science Fiction Adventure
Similarity: 0.86
--------------------
Title: The Host
Genre: Action Adventure Romance Science Fiction Thriller
Similarity: 0.86
--------------------
Title: Land of the Lost
Genre: Adventure Comedy Science Fiction
Similarity: 0.85
--------------------
Title: Paul
Genre: Adventure Comedy Science Fiction
Similarity: 0.85
--------------------
Title: Hot Tub Time Machine
Genre: Science Fiction Comedy Adventure
Similarity: 0.85
--------------------
Title: Bill & Ted's Excellent Adventure
Genre: Adventure Comedy Science Fiction
Similarity: 0.85
--------------------
Title: Idiocracy
Genre: Adventure Comedy Science Fiction
Similarity: 0.85
--------------------
Title: Oblivion
Genre: Action Science Fiction Adventure Mystery
Similarity: 0.85
--------------------
Title: RoboCop 3
Genre: Action Adventure Crime Science Fiction Thriller
Similarity: 0.84
--------------------
Title: Journey to the Center of the Earth
Genre: Action Science Fiction Adventure Comedy Family
Similarity: 0.84
--------------------
Title: Spy Kids 3-D: Game Over
Genre: Action Adventure Comedy Family Science Fiction
Similarity: 0.84
--------------------
Title: Teenage Mutant Ninja Turtles II: The Secret of the Ooze
Genre: Science Fiction Adventure Action Comedy Family
Similarity: 0.84
--------------------
Title: War of the Worlds
Genre: Adventure Thriller Science Fiction
Similarity: 0.83
--------------------
Title: The Hunger Games: Mockingjay - Part 1
Genre: Science Fiction Adventure Thriller
Similarity: 0.83
--------------------
Title: Insurgent
Genre: Adventure Science Fiction Thriller
Similarity: 0.83
--------------------
Title: Hulk
Genre: Drama Action Science Fiction
Similarity: 0.83
--------------------
Title: Real Steel
Genre: Action Science Fiction Drama
Similarity: 0.83
--------------------
Title: Snowpiercer
Genre: Action Science Fiction Drama
Similarity: 0.83
--------------------
Title: Blade: Trinity
Genre: Science Fiction Action Horror Thriller Adventure
Similarity: 0.83
--------------------
Title: Anacondas: The Hunt for the Blood Orchid
Genre: Adventure Action Horror Science Fiction Thriller
Similarity: 0.83
--------------------
Title: Teenage Mutant Ninja Turtles
Genre: Science Fiction Action Adventure Fantasy Comedy
Similarity: 0.83
--------------------
Title: Mystery Men
Genre: Adventure Fantasy Action Comedy Science Fiction
Similarity: 0.83
--------------------
Title: Small Soldiers
Genre: Comedy Adventure Fantasy Science Fiction Action
Similarity: 0.83
--------------------
Title: Superman III
Genre: Comedy Action Adventure Fantasy Science Fiction
Similarity: 0.83
--------------------
Title: Sheena
Genre: Action Adventure Comedy Fantasy Science Fiction
Similarity: 0.83
--------------------
Title: Congo
Genre: Action Adventure Drama Mystery Science Fiction
Similarity: 0.82
--------------------
Title: Knowing
Genre: Action Adventure Drama Mystery Science Fiction
Similarity: 0.82
--------------------
Title: Men in Black 3
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: The Adventures of Pluto Nash
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: The Stepford Wives
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: Pixels
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: Superhero Movie
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: The World's End
Genre: Comedy Action Science Fiction
Similarity: 0.82
--------------------
Title: Attack the Block
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: The Ice Pirates
Genre: Action Science Fiction Comedy
Similarity: 0.82
--------------------
Title: The Helix... Loaded
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: American Hero
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: Death Race 2000
Genre: Action Comedy Science Fiction
Similarity: 0.82
--------------------
Title: The Fifth Element
Genre: Adventure Fantasy Action Thriller Science Fiction
Similarity: 0.82
--------------------
Title: The Shadow
Genre: Adventure Fantasy Action Thriller Science Fiction
Similarity: 0.82
--------------------
Title: Underworld: Rise of the Lycans
Genre: Fantasy Action Adventure Science Fiction Thriller
Similarity: 0.82
--------------------
Title: Dragonball Evolution
Genre: Action Adventure Fantasy Science Fiction Thriller
Similarity: 0.82
--------------------
Title: The Astronaut Farmer
Genre: Adventure Comedy Drama Science Fiction
Similarity: 0.81
--------------------
Title: Inception
Genre: Action Thriller Science Fiction Mystery Adventure
Similarity: 0.81
--------------------
Title: Sky Captain and the World of Tomorrow
Genre: Mystery Action Thriller Science Fiction Adventure
Similarity: 0.81
--------------------
Title: Paycheck
Genre: Action Adventure Mystery Science Fiction Thriller
Similarity: 0.81
--------------------
Title: Terminator Salvation
Genre: Action Science Fiction Thriller
Similarity: 0.8
--------------------
Title: Terminator 3: Rise of the Machines
Genre: Action Thriller Science Fiction
Similarity: 0.8
--------------------
Title: Terminator 2: Judgment Day
Genre: Action Thriller Science Fiction
Similarity: 0.8
--------------------
Title: Hollow Man
Genre: Action Science Fiction Thriller
Similarity: 0.8
--------------------